name: traefik

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - "--api=true" # Enable the Traefik API
      - "--api.dashboard=true" # Enable the Traefik dashboard
      - "--log.level=DEBUG" # Set log level to DEBUG for detailed logs
      - "--providers.docker=true" # Enable Docker provider
      - "--providers.docker.exposedbydefault=false" # Only expose containers with explicit labels
      - "--entrypoints.traefik.address=:8080" # Define entry point for Traefik dashboard
      - "--entrypoints.web.address=:80" # Define entry point for HTTP
      - "--entrypoints.websecure.address=:443" # Define entry point for HTTPS
      - "--certificatesresolvers.cert-resolver.acme.httpchallenge.entrypoint=web" # Use HTTP challenge for ACME
      - "--certificatesresolvers.cert-resolver.acme.email=support@bikram-rai.com" # Set email for ACME registration
      - "--certificatesresolvers.cert-resolver.acme.storage=/letsencrypt/acme.json" # Define storage for ACME certificates
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure" # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https" # Redirect HTTP to HTTPS

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Mount Docker socket for Traefik to access Docker API
      - "./certificates/letsencrypt:/letsencrypt" # Mount directory for ACME certificates

    ports:
      - "80:80" # Expose HTTP port
      - "443:443" # Expose HTTPS port
    networks:
      - traefik_network
      - project-a-network

networks:
  traefik_network:
    name: traefik_network
  project-a-network:
    name: project-a-network
